# Generated by Django 2.2.4 on 2019-09-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='votes',
            new_name='votes_total',
        ),
    ]
