# Generated by Django 2.2.4 on 2019-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190902_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes_total',
            field=models.BigIntegerField(default=1),
        ),
    ]
